import { useEffect, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { PAGES } from '../content/pages'
import { scene, PRODUCT_ART, APP_ART, BENEFIT_ART, BACKGROUNDS } from '../content/v6-photography'
import { Icono } from '../panel/Iconos'
import { MarketingFooter } from '../components/marketing/MarketingChrome'
import { ContactForm } from '../components/marketing/MarketingSections'
import ScenePhoto from '../components/marketing/ScenePhoto'
import '../styles/reference-v6.css'
import '../styles/photography-v6.css'
import '../styles/sections-v6.css'

const LABELS={plataforma:'Plataforma web',app:'App',funciones:'Funciones',seguridad:'Seguridad',areas:'Áreas',contacto:'Contacto','quienes-somos':'Quiénes somos','que-ofrecemos':'Qué ofrecemos',beneficios:'Beneficios','preguntas-frecuentes':'Preguntas frecuentes'}
const iconFor=(text='')=> /correo|mensaje|comunicaci/i.test(text)?'mensaje':/persona|equipo|rol|conductor|usuario|perfil/i.test(text)?'gente':/mantenimiento|servicio|instalaci|cuidado/i.test(text)?'llave':/mapa|zona|ubicaci|posici|área|ruta/i.test(text)?'pin':/alerta|aviso|riesgo|falla/i.test(text)?'alerta':/historial|tiempo/i.test(text)?'reloj':/reporte|decisi|indicador/i.test(text)?'reporte':/document|registro|lista/i.test(text)?'documento':/inspecci|revisi|verific/i.test(text)?'inspeccion':/vehículo|unidad|flota|seguimiento/i.test(text)?'camion':/seguridad|cifrado/i.test(text)?'escudo':'resumen'
const facts=(...items)=>items.map(item=>typeof item==='string'?{label:item,text:''}:{label:item[0],text:item[1]})
function Button({to='/contacto#solicitud-demo',children='Solicitar una demostración'}){return <Link className="r-button" to={to}>{children}<span aria-hidden="true">→</span></Link>}

function Art({visual,...props}){return <ScenePhoto scene={visual} {...props}/>}
function Facts({items=[],cards=false}){return <ul className={`r-facts ${cards?'r-fact-cards':''}`}>{items.map(b=><li key={b.label}><span className="r-icon"><Icono nombre={iconFor(b.label)} tam={25}/></span><div><h3>{b.label.replace(/^\d+\.\s*/, '')}</h3>{b.text&&<p>{b.text}</p>}</div></li>)}</ul>}
function Metric({stat}){return stat&&<div className="r-metric"><Icono nombre={iconFor(stat.label)} tam={28}/><strong>{stat.value}</strong><span>{stat.label}</span></div>}
function Row({title,body,items,visual,reverse=false,eyebrow,stat,children,id,className=''}){const photoStat=/r-plataforma-(1|3|5)|r-areas-1|r-seguridad-4/.test(className);return <section id={id} className={`r-row ${reverse?'r-reverse':''} ${className}`}><div className="r-copy">{eyebrow&&<span className="r-eyebrow">{eyebrow}</span>}<h2>{title}</h2>{body&&<p>{body}</p>}<Facts items={items}/>{children}{!photoStat&&<Metric stat={stat}/>}</div>{visual&&(photoStat?<div className="r-visual"><Art visual={visual} alt="Escena de la propuesta FOM: operación y pantallas con datos de demostración."/><Metric stat={stat}/></div>:<Art visual={visual} alt="Escena de la propuesta FOM: operación y pantallas con datos de demostración."/>)}</section>}
function Hero({title,body,visual,eyebrow,center=false,children,button=true}){return <header className={`r-hero ${center?'r-hero-center':''}`}><div className="r-copy">{eyebrow&&<span className="r-eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{body}</p>{button&&<Button/>}{children}</div><Art visual={visual} priority alt="FOM: flotas, personas y operación. Pantallas con datos de demostración."/></header>}
function CTA({title='Conoce FOM con tu equipo',body='Descubre cómo un solo panel puede simplificar la gestión de tu flota.',visual=scene('cta-road')}){return <section className="r-cta"><div className="r-copy"><h2>{title}</h2><p>{body}</p><Button/></div><Art visual={visual}/></section>}
function FAQs({items=PAGES.plataforma.faqs,title='Preguntas frecuentes',layout='',initialOpen=false}){return <section className={`r-faq ${layout}`}><div className="r-faq-heading"><div><h2>{title}</h2><p>Resuelve tus dudas principales.</p></div><a href="mailto:contacto@fom.app">¿Tienes otra pregunta?<br/><b>contacto@fom.app →</b></a></div><div className="r-questions">{items.map((f,i)=><details key={f.q} open={initialOpen&&i===0?true:undefined}><summary>{f.q}<span aria-hidden="true">+</span></summary><p>{f.a}</p></details>)}</div></section>}

function Home(){return <>
  <Hero title={<>Tu flota conectada.<br/>Tu operación, bajo control.</>} body="La oficina y la carretera, en una misma plataforma." eyebrow="Flotas que mantienen el mundo en movimiento" visual={scene('home-hero')}/>
  <Row className="r-home-phone" title={<>Todo ese control.<br/>Ahora en tu mano.</>} body="De la vista completa de tu flota a la unidad que acompaña a tu conductor." visual={scene('home-phone')} items={facts(['La misma información','Tu equipo en campo y la oficina siempre alineados.'],['Datos en tiempo real','Lo que pasa en la ruta, al alcance de tu mano.'],['Una operación conectada','Vehículos, conductores y tareas en un mismo lugar.'])}/>
  <Row id="quienes-somos" className="r-home-intro" title="La operación se entiende mejor cuando todos ven lo mismo." body="FOM reúne el trabajo de la oficina y del equipo en campo en una sola plataforma para flotas. Seguimiento, cuidado del vehículo y comunicación forman parte de una misma operación." visual={scene('home-team')} reverse><div className="r-service-cards">{[['Seguimiento','Ubicación, recorridos y estado de cada vehículo.','/plataforma'],['Cuidado','Inspecciones, documentos y mantenimiento.','/funciones'],['Decisiones','Alertas, seguridad y reportes para la operación.','/seguridad']].map(([h,p,to])=><Link to={to} key={h}><Icono nombre={iconFor(h)} tam={32}/><h3>{h}</h3><p>{p}</p></Link>)}</div></Row>
  <Row id="plataforma" title={<>Toda la operación.<br/>Una sola vista.</>} body="Vehículos, alertas y mantenimiento conectados para decidir con claridad." visual={scene('home-panel')} items={facts(['Flota en tiempo real','Ubica tus unidades en el mapa.'],['Estado de la operación','Consulta alertas y pendientes.'],['Información integrada','De la ruta al mantenimiento.'])}/>
  <Row id="app" title="La operación también viaja con tu equipo." body="FOM DRIVER conecta al conductor con su unidad y con la oficina. Inicio, inspección y perfil en una misma app." visual={scene('home-driver')} reverse items={facts(['Inicio','Estado de la unidad en tiempo real.'],['Inspección','Checklist desde la app.'],['Perfil','Información y documentos del conductor.'])}/>
  <Row id="funciones" title={<>Del primer chequeo<br/>al próximo servicio.</>} body="Un recorrido conectado: revisar, reportar y dar seguimiento." visual={scene('home-maintenance')} items={facts(['Inspecciones en campo','Registra condiciones de la unidad.'],['Mantenimiento','Consulta próximos servicios.'],['Historial','Toda la información, siempre disponible.'])}/>
  <section className="r-safety-areas"><Art visual={scene('home-profile')} alt="Perfil del conductor e índice de manejo, datos de demostración."/><div className="r-copy"><Link to="/seguridad"><h2>Conducir mejor empieza por entender cada viaje.</h2></Link><p>Un índice claro para acompañar al conductor y atender lo que necesita mejorar.</p><Facts items={facts(['Índice de manejo seguro','Evalúa cada viaje.'],['Retroalimentación clara','Identifica áreas de mejora.'],['Conductores más preparados','Una flota más segura y eficiente.'])}/></div><div className="r-copy"><Link to="/areas"><h2>Un mismo control.<br/>Cada zona de tu flota.</h2></Link><p>Organiza unidades por área y consulta su ubicación desde la consola.</p><Art visual={scene('home-areas')} alt="Mapa ilustrativo de zonas de la flota."/></div></section>
  <section className="r-contact r-contact-compact" id="contacto"><div className="r-copy"><h2>Hablemos de tu operación</h2><p>Cuéntanos cómo trabajas y coordinamos una demostración.</p></div><ContactForm/></section>
  <FAQs layout="r-faq-home"/>
 </>}

function Product({slug}){const p=PAGES[slug],art=PRODUCT_ART[slug];return <>
  <Hero title={p.title} body={p.subtitle} eyebrow={p.eyebrow} visual={art.hero} center={slug==='areas'} button={slug!=='areas'}/>
  {p.sections.map((s,i)=>{
    if(slug==='contacto'&&i===0)return <section className="r-contact" id="detalle-0" key={s.heading}><div className="r-copy"><h2>{s.heading}</h2><p>{s.body}</p><Facts items={s.bullets}/><Metric stat={s.stat}/></div><ContactForm/></section>
    if(slug==='contacto'&&i===1)return <section className="r-process" id="detalle-1" key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p><ol>{s.bullets.map((b,j)=><li key={b.label}><span className="r-process-icon"><Icono nombre={['mensaje','resumen','documento','llave','inspeccion'][j]} tam={32}/></span><h3>{b.label}</h3><p>{b.text}</p></li>)}</ol></section>
    return <Row key={s.heading} id={`detalle-${i}`} className={`r-${slug}-${i}`} title={art.titles?.[i]||s.heading} eyebrow={art.titles?s.heading:undefined} body={s.body} items={slug==='contacto'&&i===2?[]:s.bullets} visual={art.rows[i]} reverse={art.reverse[i]} stat={s.stat}>{slug==='contacto'&&i===2&&<div className="r-channel-grid">{s.bullets.map(b=><a key={b.label} href={b.label==='Correo'?'mailto:contacto@fom.app':'#solicitud-demo'}><Icono nombre={iconFor(b.label)} tam={25}/><h3>{b.label}</h3><p>{b.text}</p>{b.label==='Correo'&&<b>contacto@fom.app</b>}</a>)}</div>}</Row>
  })}
  <div className={slug==='areas'?'r-end-split':''}><FAQs items={p.faqs} layout={slug==='plataforma'?'r-faq-columns':slug==='funciones'?'r-faq-four':''} initialOpen={slug==='funciones'}/>{slug!=='contacto'&&<CTA/>}</div>
 </>}

const APP_ROWS=[
 ['Inspección','Una inspección que queda registrada.','Revisa los puntos de la unidad y registra su condición desde el teléfono. La información permite dar seguimiento a los hallazgos desde la oficina.',facts('Lista de revisión por vehículo.','Registro de observaciones y fallas.','Historial disponible para la operación.')],
 ['Inicio','El estado de tu unidad, a mano.','Desde Inicio, el conductor consulta la información de su vehículo y encuentra accesos a inspecciones, mantenimiento y alertas.',facts('Información en tiempo real.','Accesos rápidos a las tareas.','Alertas en la jornada.')],
 ['Perfil','Conoce tu índice de manejo.','Consulta tus datos, documentos y el índice de conducción. Sus indicadores ayudan a entender qué aspectos del manejo requieren atención.',facts('Indicadores de tu manejo.','Documentos siempre a mano.','Tu información en un solo lugar.')],
]
function AppPage(){return <><Hero title="Tu unidad y tu jornada, en tu teléfono." body="Consulta el estado del vehículo, realiza la inspección y revisa tu perfil desde la app que acompaña al conductor." eyebrow="App del conductor" visual={scene('app-hero')}/>{APP_ROWS.map(([key,title,body,items],i)=><Row key={key} title={title} body={body} items={items} eyebrow="App del conductor" visual={APP_ART[i]} className="r-app-row"/>)}<CTA title="La oficina y el conductor, conectados." body="Conoce el panel web y la app con una demostración de FOM." visual={scene('app-office')}/></>}
const BENEFITS=[
 ['Visibilidad de la operación','Consulta ubicación, estado y responsable de cada unidad desde una misma vista.',facts('Ubicación en tiempo real','Estado y responsable','Toda la flota en un solo lugar')],
 ['Cuidado de cada vehículo','Reúne inspecciones, hallazgos y órdenes de mantenimiento para dar seguimiento a lo que necesita cada unidad.',facts('Inspecciones en campo','Hallazgos y mantenimientos','Seguimiento por unidad')],
 ['Comunicación desde el campo','El conductor registra información desde su teléfono y la oficina la consulta en la plataforma.',facts('Registro desde el teléfono','Información disponible en la oficina','Trabajo conectado')],
 ['Atención a las alertas','Encuentra los avisos que requieren revisión y consulta el contexto de los eventos.',facts('Alertas en tiempo real','Eventos de manejo','Reglas y notificaciones')],
 ['Organización por áreas','Agrupa unidades por zona, sede o contrato para consultar la parte de la flota que te corresponde.',facts('Zonas y sedes','Contratos y agrupaciones','Vista de la flota por área')],
 ['Información para decidir','Consulta reportes e historial para revisar la operación y planificar los siguientes pasos.',facts('Reportes de operación','Historial de actividad','Datos para la planificación')],
]
function Benefits(){return <><Hero title="Más claridad para cada decisión de tu flota." body="FOM conecta el trabajo de campo con la oficina para que la información sirva al seguimiento diario de la operación." eyebrow="Beneficios" visual={scene('benefits-hero')}/>{BENEFITS.map(([title,body,items],i)=><Row key={title} title={title} body={body} items={items} visual={BENEFIT_ART[i]} reverse={i%2===0} eyebrow={`0${i+1}.`} className="r-benefit-row"/>)}<CTA title="Encuentra las herramientas para tu operación." body="Conoce el panel web y la app con una demostración de FOM." visual={scene('cta-road')}/></>}
function Services(){return <><Hero title="Una plataforma para seguir, cuidar y entender tu flota." body="Herramientas conectadas para el trabajo diario, desde el panel de control hasta la app del conductor." visual={scene('services-hero')} eyebrow="Flotas que mantienen el mundo en movimiento"><div className="r-indicators">{['Más control en tu operación','Información para decidir','Flotas más eficientes'].map(t=><span key={t}><Icono nombre={iconFor(t)} tam={25}/>{t}</span>)}</div></Hero>
  <Row className="r-service-row" id="servicio-01" title="Consulta dónde están las unidades y revisa sus trayectos desde el centro de control." body="Visualiza la flota en tiempo real, filtra por estado y accede al detalle de cada unidad." eyebrow="Ubicación y recorridos" visual={scene('services-map')}/>
  <Row className="r-service-row" id="servicio-02" title="El conductor revisa la unidad desde la app; la oficina consulta hallazgos y da seguimiento al servicio." body="Menos imprevistos y más tiempo en movimiento." eyebrow="Inspecciones y mantenimiento" visual={scene('services-inspection')} reverse/>
  <Row className="r-service-row" id="servicio-03" title="Los avisos y los datos de la flota ayudan a priorizar lo que requiere atención y a entender cada recorrido." body="Recibe notificaciones, revisa eventos de manejo y mantén tu operación al día." eyebrow="Alertas, seguridad y reportes" visual={scene('services-alerts')}/>
  <CTA title="Ve cómo encaja FOM con tu operación." body="Revisamos tu flota y te mostramos el panel y la app en una demostración." visual={scene('cta-road')}/></>}
const ABOUT_FAQ=[{q:'¿Qué es FOM?',a:'Una plataforma que conecta a las personas, los vehículos y la información de una operación en movimiento.'},{q:'¿Quién puede usar la plataforma?',a:'Los responsables de la operación trabajan desde el panel web y los conductores desde la app, con acceso según su rol.'},{q:'¿Necesito instalar algo?',a:PAGES.plataforma.faqs[0].a}]
function About(){return <><header className="r-about-hero"><Art visual={scene('about-hero')} priority alt="Equipo FOM en la oficina frente al panel de la flota, datos de demostración."/><div className="r-copy"><span className="r-eyebrow">Quiénes somos</span><h1>Una forma más clara de cuidar y coordinar tu flota.</h1><p>FOM es una plataforma para conectar a las personas, los vehículos y la información de una operación en movimiento.</p></div></header>
  <Row title="La oficina y la carretera, conectadas." body="Una flota genera decisiones a cada momento: dónde está una unidad, qué necesita para salir y qué ocurrió en el camino." eyebrow="Nuestra forma de trabajar" visual={scene('about-driver')}><p>FOM reúne esas respuestas en el panel web y en la app del conductor.</p><p>El objetivo es que cada persona encuentre la información que necesita para actuar: supervisores desde la consola y conductores desde su teléfono.</p></Row>
  <Row title="De cada dato a una acción concreta." body="Los recorridos, las alertas, las inspecciones y el mantenimiento comparten una misma vista de la operación." eyebrow="Todo en contexto" visual={scene('about-road')}><p>Así es más sencillo revisar lo que pasa y dar seguimiento sin perder el contexto.</p></Row>
  <section className="r-principles"><span className="r-eyebrow">Nuestros principios</span><h2>Una operación más conectada.</h2><div>{[['Conectar','Vehículos, conductores y responsables en un mismo flujo.','principle-connect'],['Entender','Ubicación, historial y estado claros para cada rol.','principle-understand'],['Actuar','Alertas e inspecciones que permiten atender lo importante.','principle-act']].map(([h,p,x])=><article key={h}><div><Icono nombre={iconFor(h)} tam={30}/><h3>{h}</h3><p>{p}</p></div><Art visual={scene(x)}/></article>)}</div></section>
  <CTA title="Conoce la operación detrás de cada pantalla." body="Sigamos en movimiento. Hablemos de tu flota." visual={scene('cta-road')}/><FAQs items={ABOUT_FAQ}/></>}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
function Help(){const [search,setSearch]=useState('');const [topic,setTopic]=useState('');const groups=Object.entries(PAGES).map(([slug,p])=>({slug,items:p.faqs.filter(f=>(!topic||slug===topic)&&normalize(f.q+' '+f.a).includes(normalize(search)))}));const count=groups.reduce((n,g)=>n+g.items.length,0);return <><Hero title="Preguntas frecuentes." body="Explora las preguntas sobre la plataforma, las funciones y la puesta en marcha." eyebrow="La oficina y la carretera, conectadas" visual={scene('help-hero')} button={false}/><section className="r-help" id="preguntas"><label className="r-search"><span className="sr-only">Buscar preguntas</span><Icono nombre="buscar" tam={20}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar preguntas…"/></label><nav aria-label="Temas de preguntas">{[['','Todos los temas'],...Object.keys(PAGES).map(k=>[k,LABELS[k]])].map(([k,v])=><button key={k} aria-pressed={topic===k} onClick={()=>setTopic(k)}><Icono nombre={iconFor(v)} tam={22}/>{v}</button>)}</nav><div className="r-help-content"><p className="sr-only" role="status">{count} preguntas encontradas</p>{groups.filter(g=>g.items.length).map(g=><FAQs key={g.slug} title={LABELS[g.slug]} items={g.items} initialOpen/>)}{!count&&<div className="r-empty"><h2>No encontramos esa pregunta.</h2><p>Prueba con otra palabra o consulta todos los temas.</p><button className="r-button" onClick={()=>{setSearch('');setTopic('')}}>Ver todas las preguntas</button></div>}</div></section><CTA title="¿Aún tienes preguntas?" visual={scene('help-contact')}/></>}
const EXTRA={app:AppPage,beneficios:Benefits,'quienes-somos':About,'que-ofrecemos':Services,'preguntas-frecuentes':Help}
export default function ReferenceMarketing(){const {pathname}=useLocation();const slug=pathname.slice(1);const Page=EXTRA[slug];useEffect(()=>{document.title=`${LABELS[slug]||'Tu flota conectada'} — FOM`},[slug]);return <main id="contenido" className={`fom-site reference-site r-route-${slug||'inicio'}`} style={{'--road-photo':`url(${BACKGROUNDS.road})`,'--office-photo':`url(${BACKGROUNDS.office})`,'--winding-photo':`url(${BACKGROUNDS.winding})`}} key={slug}>{!slug?<Home/>:PAGES[slug]?<Product slug={slug}/>:Page?<Page/>:<section className="r-not-found"><h1>Esta ruta no está en el mapa.</h1><Button to="/">Volver al inicio</Button></section>}<MarketingFooter/></main>}
